#ifndef QTC_CHAINPARAMSSEEDS_H
#define QTC_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the quartercoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x8a,0x44,0x3d,0xc7}, 42671},
    
};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x7f,0x00,0x00,0x01}, 48145}
};
#endif // QTC_CHAINPARAMSSEEDS_H

/* Mainnet Seed Nodes

165.22.57.66.22

*/

